package Project.Common;

//as4555 3/26/24
public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CREATE_ROOM, JOIN_ROOM, LIST_ROOMS, CLIENT_ID, SYNC_CLIENT, READY, PHASE, TURN, RESET_TURNS, RESET_READY, 
    CATEGORY_QUESTION, ANSWER_CHOICE, RESET_CORRECTNESS, ROUND_NUM, RESET_ROUND_NUM,
    //as4555 4/14/24
    TIME_LEFT, SCORE, SORT_USERS, WINNER_MESSAGE,
    //as4555 4/24/24
    AWAY, BACK,
    //as4555 4/27/24
    ADD_QUESTION, NEW_QUES,
    //as4555 4/28/24
    CAT_PRESS, CAT_OPTIONS
}